sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_intall:
  - cd 17_RestWithASPNETUdemy_Docker/RestWithASPNETUdemy
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net-udemy:lastest $DOCKER_USERNAME/RestWithASP-NET5Udemy:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net-udemy-db:lastest $DOCKER_USERNAME/RestWithASP-NET5Udemy:$TRAVIS_JOB_ID;
    docker push rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    docker push rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email:false